### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by ddehghan** [Wonderfall/docker-matomo#2]
Hi, Thanks for creating this repo. I almost got it to work but then restarted the container and it stopped working. I think the problem is the logic of copying the config file. 

it would be great is you can add the docker-compose file. I made one you can start with:

```
version: "3"
services:
  matomo:
    container_name: matomo
    image: wonderfall/matomo
    links:
      - db_matomo:db_matomo
    volumes:
      - ./matomo/config:/config
    environment:
      - GID=1000
      - UID=1000
    depends_on:
      - db_matomo
    ports:
     - 8888:8888
    networks:
      - backend

  db_matomo:
    container_name: db_matomo
    image: mariadb:10
    volumes:
      - ./matomo/db:/var/lib
    environment:
      - MYSQL_ROOT_PASSWORD=asupersecretpassword
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=asupersecretpassword
    networks:
      - backend

networks:
  backend:
    external:
      name: backend

```

I also created these:
```
mkdir -p ./matomo/config
mkdir -p ./matomo/db
```

It seems that if the  ./matomo/config is empty you try to copy some file into it. But that files does not seem to exist or it had been overwritten. 

I get this on the matomo container when starting a clean run with both ./matomo/db and ./matomo/config directories empty.

```
> docker logs matomo
cp: can't stat '/matomo/config/config.ini.php': No such file or directory

```

I am going to send you a pull request if I can get it to work. But I am close to giving up.

Thanks
David
